language: rust

script:
  - cargo update
  - cargo build --no-default-features --features=$FEATURE
  - cargo test --no-default-features --features=$FEATURE

env:
  global:
    - RUST_BACKTRACE=1

jobs:
  include:
    - os: linux
      dist: trusty
      sudo: false
      env: FEATURE=source
      addons:
        apt:
          packages:
            - gcc
            - make
    - os: linux
      dist: trusty
      sudo: false
      env: FEATURE=system
      addons:
        apt:
          packages:
            - libfftw3-dev
    - os: linux
      dist: trusty
      sudo: false
      env: FEATURE=intel-mkl
    - os: osx
      env: FEATURE=source
    - os: osx
      env: FEATURE=intel-mkl

cache:
  cargo: []
