language: rust

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

script:
  - cargo update
  - cargo build --no-default-features --features=$FEATURE
  - cargo test --no-default-features --features=$FEATURE

env:
  global:
    - RUST_BACKTRACE=1

jobs:
  include:
    - env: FEATURE=source
      addons:
        apt:
          packages:
            - gcc
            - make
    - env: FEATURE=system
      addons:
        apt:
          packages:
            - libfftw3-dev
    - env: FEATURE=intel-mkl

cache:
  cargo: []
