jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        source:
          feature: source
        intel-mkl:
          feature: intel-mkl
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: cargo test -v --features=$FEATURE --no-default-features
        displayName: run test

  - job: LinuxApt
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: |
          apt update
          apt install -y libfftw3-dev
        displayName: apt install
      - script: cargo test -v --features=$FEATURE --no-default-features
        displayName: run test

  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    strategy:
      matrix:
        source:
          feature: source
        intel-mkl:
          feature: intel-mkl
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: cargo test -v --features=$FEATURE --no-default-features
        displayName: run test
