parameters:
  pool: ''
  name: ''

jobs:
  - job:  ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    strategy:
      matrix:
        source:
          feature: source
        system:
          feature: system
        intel-mkl:
          feature: intel-mkl
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: cargo test -v --features=$FEATURE --no-default-feature
        displayName: run test
