name: Rust

on:
  push:
    branches:
      - master
      - "pr/*"
  pull_request: {}

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        feature: ["intel-mkl", "source"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=fftw/Cargo.toml --features=${{ matrix.feature }} --no-default-features

  macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        feature: ["intel-mkl", "source"]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=fftw/Cargo.toml --features=${{ matrix.feature }} --no-default-features

  linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        feature: ["intel-mkl", "intel-mkl-system", "system", "source"]
    steps:
    - uses: actions/checkout@v1
    - name: Install system FFTW
      run: sudo apt update && sudo apt install -y libfftw3-dev
      if: ${{ matrix.feature == 'system' }}
    - name: Install Intel-MKL by apt
      run: ./intel-mkl-apt.sh
      if: ${{ matrix.feature == 'intel-mkl-system' }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=fftw/Cargo.toml --features=${{ matrix.feature }} --no-default-features

  check-format:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
