name: Rust

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  windows-mkl:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        download: ["nuget", "ocipkg"]
    steps:
    - uses: actions/checkout@v1
    - name: Get MKL using NuGet
      if: ${{ matrix.download == 'nuget' }}
      run: |
        nuget install intelmkl.devel.cluster.win-x64  -Version 2022.0.3.171
        nuget install intelmkl.static.cluster.win-x64 -Version 2022.0.3.171
        echo "${{ github.workspace }}/intelmkl.redist.win-x64.2022.0.3.171/runtimes/win-x64/native" >> $Env:GITHUB_PATH
        echo "${{ github.workspace }}/intelopenmp.redist.win.2022.0.0.3663/runtimes/win-x64/native" >> $Env:GITHUB_PATH
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --all-targets
          --manifest-path=fftw/Cargo.toml
          --features=intel-mkl
          --no-default-features

  windows-source:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: >
          --all-targets
          --manifest-path=fftw/Cargo.toml
          --features=source
          --no-default-features

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        feature: ["source", "system"]
    steps:
    - uses: actions/checkout@v1
    - name: Install system FFTW
      run: brew install fftw
      if: ${{ matrix.feature == 'system' }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=fftw/Cargo.toml --features=${{ matrix.feature }} --no-default-features

  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        feature: ["intel-mkl", "system", "source"]
    steps:
    - uses: actions/checkout@v1
    - name: Install system FFTW
      run: sudo apt update && sudo apt install -y libfftw3-dev
      if: ${{ matrix.feature == 'system' }}
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --manifest-path=fftw/Cargo.toml --features=${{ matrix.feature }} --no-default-features

  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
